### ISSUE TITLE
Maven repos are not found when building latest indexer

### ISSUE THREAD

**Issue by hemantranvir** [rarible/ethereum-indexer#436] opened 2022-08-09 14:36 UTC
When building, looks like the maven repos for older versions are not found on rarible's or central's maven repo urls

```
Downloading from nexus-ext-maven-public: https://repo.rarible.org/repository/maven-public/com/rarible/core/rarible-core-parent/2.4.9/rarible-core-parent-2.4.9.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/rarible/core/rarible-core-parent/2.4.9/rarible-core-parent-2.4.9.pom
Downloading from nexus-ext-maven-public: https://repo.rarible.org/repository/maven-public/com/rarible/core/rarible-core-parent/2.3.8/rarible-core-parent-2.3.8.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/rarible/core/rarible-core-parent/2.3.8/rarible-core-parent-2.3.8.pom
Downloading from nexus-ext-maven-public: https://repo.rarible.org/repository/maven-public/com/rarible/ethereum/rarible-ethereum-parent/1.5.7/rarible-ethereum-parent-1.5.7.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/rarible/ethereum/rarible-ethereum-parent/1.5.7/rarible-ethereum-parent-1.5.7.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact com.rarible.core:rarible-core-parent:pom:2.4.9 in nexus-ext-maven-public (https://repo.rarible.org/repository/maven-public/) @ com.rarible.ethereum:rarible-ethereum-parent:1.6.0, /home/hemant/.m2/repository/com/rarible/ethereum/rarible-ethereum-parent/1.6.0/rarible-ethereum-parent-1.6.0.pom, line 53, column 19
[ERROR] Non-resolvable import POM: Could not find artifact com.rarible.core:rarible-core-parent:pom:2.3.8 in nexus-ext-maven-public (https://repo.rarible.org/repository/maven-public/) @ com.rarible.protocol.ethereum:rarible-ethereum-openapi:1.33.0, /home/hemant/.m2/repository/com/rarible/protocol/ethereum/rarible-ethereum-openapi/1.33.0/rarible-ethereum-openapi-1.33.0.pom, line 81, column 19
[ERROR] Non-resolvable import POM: Could not find artifact com.rarible.ethereum:rarible-ethereum-parent:pom:1.5.7 in nexus-ext-maven-public (https://repo.rarible.org/repository/maven-public/) @ com.rarible.protocol.ethereum:rarible-ethereum-openapi:1.33.0, /home/hemant/.m2/repository/com/rarible/protocol/ethereum/rarible-ethereum-openapi/1.33.0/rarible-ethereum-openapi-1.33.0.pom, line 88, column 19
[ERROR] Non-resolvable import POM: com.rarible.core:rarible-core-parent:pom:2.4.9 was not found in https://repo.rarible.org/repository/maven-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-ext-maven-public has elapsed or updates are forced @ com.rarible.ethereum:rarible-ethereum-parent:1.6.0, /home/hemant/.m2/repository/com/rarible/ethereum/rarible-ethereum-parent/1.6.0/rarible-ethereum-parent-1.6.0.pom, line 53, column 19
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.rarible.protocol:rarible-protocol-ethereum-indexer:1.32 (/home/hemant/work/indexer/rarible/ethereum-indexer-temp/pom.xml) has 4 errors
[ERROR]     Non-resolvable import POM: Could not find artifact com.rarible.core:rarible-core-parent:pom:2.4.9 in nexus-ext-maven-public (https://repo.rarible.org/repository/maven-public/) @ com.rarible.ethereum:rarible-ethereum-parent:1.6.0, /home/hemant/.m2/repository/com/rarible/ethereum/rarible-ethereum-parent/1.6.0/rarible-ethereum-parent-1.6.0.pom, line 53, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact com.rarible.core:rarible-core-parent:pom:2.3.8 in nexus-ext-maven-public (https://repo.rarible.org/repository/maven-public/) @ com.rarible.protocol.ethereum:rarible-ethereum-openapi:1.33.0, /home/hemant/.m2/repository/com/rarible/protocol/ethereum/rarible-ethereum-openapi/1.33.0/rarible-ethereum-openapi-1.33.0.pom, line 81, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not find artifact com.rarible.ethereum:rarible-ethereum-parent:pom:1.5.7 in nexus-ext-maven-public (https://repo.rarible.org/repository/maven-public/) @ com.rarible.protocol.ethereum:rarible-ethereum-openapi:1.33.0, /home/hemant/.m2/repository/com/rarible/protocol/ethereum/rarible-ethereum-openapi/1.33.0/rarible-ethereum-openapi-1.33.0.pom, line 88, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: com.rarible.core:rarible-core-parent:pom:2.4.9 was not found in https://repo.rarible.org/repository/maven-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-ext-maven-public has elapsed or updates are forced @ com.rarible.ethereum:rarible-ethereum-parent:1.6.0, /home/hemant/.m2/repository/com/rarible/ethereum/rarible-ethereum-parent/1.6.0/rarible-ethereum-parent-1.6.0.pom, line 53, column 19 -> [Help 2]
[ERROR] 
```

**Comment by chenji23** [comment] 2022-08-09 17:08
same issue +1

**Comment by atapin** [comment] 2022-08-23 11:19
@hemantranvir @chenji23 we had some problems with maven repos. could you try again?

**Comment by chenji23** [comment] 2022-08-23 22:00
[ERROR] Failed to execute goal on project rarible-protocol-ethereum-indexer: Could not resolve dependencies for project com.rarible.protocol:rarible-protocol-ethereum-indexer:pom:1.34: The following artifacts could not be resolved: io.daonomic.scalether:transport-mono_2.13:jar:0.1.4, io.daonomic.scalether:transaction-mono_2.13:jar:0.1.4, io.daonomic.scalether:domain-test_2.13:jar:0.1.4: Could not find artifact io.daonomic.scalether:transport-mono_2.13:jar:0.1.4 in nexus-ext-maven-public (https://repo.rarible.org/repository/maven-public/) -> [Help 1]

**Comment by ayushdeqode** [comment] 2022-08-30 07:26
++1

**Comment by shivraj001** [comment] 2022-09-01 15:10
[ERROR] Failed to execute goal on project rarible-protocol-ethereum-indexer: Could not resolve dependencies for project com.rarible.protocol:rarible-protocol-ethereum-indexer:pom:1.35: The following artifacts could not be resolved: io.daonomic.scalether:transport-mono_2.13:jar:0.1.4, io.daonomic.scalether:transaction-mono_2.13:jar:0.1.4, io.daonomic.scalether:domain-test_2.13:jar:0.1.4: Failure to find io.daonomic.scalether:transport-mono_2.13:jar:0.1.4 in https://repo.rarible.org/repository/maven-public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus-ext-maven-public has elapsed or updates are forced -> [Help 1]
@atapin i got the same error

**Comment by IssyPro101** [comment] 2022-09-03 06:22
Also having this issue +1

**Comment by DmitryShut** [comment] 2022-10-06 13:09
@atapin hello, maybe you have some updates, about repos?

**Comment by atapin** [comment] 2022-10-10 06:50
@evgenynacu @sanufriev can you guys help?

**Comment by evgenynacu** [comment] 2022-10-12 11:39
It will take some more time, need to diagnose those issues more, not found the cause yet

**Comment by evgenynacu** [comment] 2022-10-12 20:02
I think it's fixed now
Deleted local repo and reimported the project - everything's find for me

Close the issue. If there's a problem, reopen pls

**Closed by evgenynacu** 2022-10-12 20:02 UTC
